### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by autsada** [hayd/deno-sparkpost#1]
Hello,

I got this error in the installation process.
`error: Import 'https://unpkg.com/lodash-es@4.17.15/isArrayLike.js' failed: 500 Internal Server Error`

Do you have any suggestions?

Thank you.

**Comment by hayd** [comment]
Perhaps unpkg was down? Can you try again?

**Comment by autsada** [comment]
Hi, now I can install it.
Thank you.

**Comment by hayd** [comment]
Very strange, hopefully it's not down often...

**Comment by autsada** [comment]
I knew you just close this issue, but I am facing a problem in trying to send an email, so could I ask in here?. 

Basically I just copied the example code. And here is my code.

```
import { SparkPost } from 'https://deno.land/x/sparkpost/mod.ts'
import { config } from 'https://deno.land/x/dotenv/mod.ts'

const { SPARKPOST_API_KEY } = config()

const client = new SparkPost(SPARKPOST_API_KEY, {
  endpoint: 'https://dev.sparkpost.com:443',
})

await client.transmissions.send(
  {
    options: { sandbox: true },
    content: {
      from: 'app@test.com',
      subject: 'Test',
      html: '<html><body><p>Testing</p></body></html>',
    },
    recipients: [{ address: 'MY EMAIL ADDRESS' }],
  },
  {}
)
```

For the client.transmissions.send(), I need to pass the second argument (I used {}) otherwise it has an error that says the send method needs 2 arguments. If I hover over the send method, the error shows as below.

```
(method) Transmissions.send(transmission: any, options: any): Promise<any>
Sends a message by creating a new transmission

@param transmission

@param options

@returns

Expected 2 arguments, but got 1.ts(2554)
```

Do you have any suggestions to make this work?

Thank you in advance.

**Comment by hayd** [comment]
I guess I should make the options optional!

**Comment by autsada** [comment]
Hi,

Sorry to bother you again.

I still got this error, and couldn't find out how to fix this issue.

```
error: Uncaught SparkPostError: 
  return new SparkPostError(res.statusMessage, body.errors, res.statusCode);
         ^
    at createSparkPostError (https://deno.land/x/sparkpost/util.ts:16:10)
    at SparkPost.request (https://deno.land/x/sparkpost/client.ts:129:13)
    at async Transmissions.send (https://deno.land/x/sparkpost/transmissions.ts:82:12)    
```

Do you have any suggestions?

I use deno v1.0.2

**Comment by hayd** [comment]
Any idea what the error was? Can you console.log the statusMessage etc ?

**Comment by autsada** [comment]
Sorry for a naive question, how I can console log the statusMessage. Here is my code.


```
import { SparkPost } from 'https://deno.land/x/sparkpost/mod.ts'
import { config } from 'https://deno.land/x/dotenv/mod.ts'

const { SPARKPOST_API_KEY } = config()

const client = new SparkPost(SPARKPOST_API_KEY, {
  endpoint: 'https://dev.sparkpost.com:443',
})

const sendEmail = async () => {
  try {
    const res = await client.transmissions.send(
      {
        options: { sandbox: true },
        content: {
          from: 'testing@sparkpostbox.com',
          subject: 'Test',
          html: '<html><body><p>Testing</p></body></html>',
        },
        recipients: [{ address: 'kakaauddy@gmail.com' }],
      },
      {}
    )

    console.log(res)
  } catch (error) {
    console.log(error)
  }
}

sendEmail()
```

And it logged the error in the console as below.

```
SparkPostError:
    at createSparkPostError (https://deno.land/x/sparkpost/util.ts:16:10)
    at SparkPost.request (https://deno.land/x/sparkpost/client.ts:129:13)
    at async Transmissions.send (https://deno.land/x/sparkpost/transmissions.ts:82:12)
```

**Comment by hayd** [comment]
I think you can do:
```
    console.log(error)
    console.log(error.message)
    console.log(error.errors)
    console.log(error.statusCode)
```
maybe it'll give more info 🤞

**Comment by autsada** [comment]
Hi

I have tried, but there is nothing print out from all these .message, .errors, and .statusCode. Here is the result.

```
error --> SparkPostError:
    at createSparkPostError (https://deno.land/x/sparkpost/util.ts:16:10)
    at SparkPost.request (https://deno.land/x/sparkpost/client.ts:129:13)
    at async Transmissions.send (https://deno.land/x/sparkpost/transmissions.ts:82:12)
    at async sendEmail (file:///C:/Users/autsa/OneDrive/Desktop/WebApp/Deno/fullstack-deno-graphql/backend/test.ts:35:17)
error.message -->
error.errors --> undefined    
error.statusCode --> undefined
```

**Comment by hayd** [comment]
Oh no, that's not a helpful message!

Perhaps you can run on a local copy of the repo and modify above this line to `console.log(await res.json())` (and the statusCode), I wonder if that  will give some more info on what the issue is. Is res.body the wrong thing here?

This repo is basically a direct port of the sparkpost node, so it looks like there are some code paths that haven't been tested, sorry about that! (TODO add tests!)

**Comment by autsada** [comment]
Ok, I will do and will update you.
Thank you for your time.
